name: CI Workflow

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  issues:
    types: 
      - opened
      - edited
      - closed
  schedule:
    - cron: "*/2 * * * *"  # Triggers every 2 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Change directory to project
      run: cd project

    - name: Install dependencies
      run: npm install
      working-directory: project

    - name: Run tests
      run: npm test
      working-directory: project

    - name: Run linter
      run: npm run lint
      working-directory: project
