name: Run Every 2 Minutes

on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a sample script
      run: echo "This job runs every 2 minutes"
